export const categories=[

    { key: '0', text: 'Kategori Seç', value: '0' },
    { key: '1', text: 'Ekmek', value: '1' },
    { key: '2', text: 'Sebze', value: '2' },
    { key: '3', text: 'İçecek', value: '3' },
    { key: '4', text: 'Tatlı', value: '4' },
    { key: '5', text: 'Meyve', value: '5' },
    { key: '6', text: 'Yemek', value: '6' },
    { key: '7', text: 'Kuru Yemiş', value: '7' },
    { key: '8', text: 'Süt ve Süt Ürünleri', value: '8' },
    { key: '9', text: 'Bitki', value: '9' },
    { key: '10', text: 'Et ve Et Ürünleri', value: '10' },
    { key: '11', text: 'Yağ', value: '11' },
    { key: '12', text: 'Atıştırmalık', value: '12' },
    { key: '13', text: 'Tuz ve Baharat', value: '13' },
]

export const cities = [
    {key: '0', text: 'Şehir Seç', value: '0'},
    {key: '1', text: 'ADANA', value: '1'},
    {key: '2', text: 'ADIYAMAN', value: '2'},
    {key: '3', text: 'AFYONKARAHİSAR', value: '3'},
    {key: '4', text: 'AĞRI', value: '4'},
    {key: '5', text: 'AMASYA', value: '5'},
    {key: '6', text: 'ANKARA', value: '6'},
    {key: '7', text: 'ANTALYA', value: '7'},
    {key: '8', text: 'ARTVİN', value: '8'},
    {key: '9', text: 'AYDIN', value: '9'},
    {key: '10', text: 'BALIKESİR', value: '10'},
    {key: '11', text: 'BİLECİK', value: '11'},
    {key: '12', text: 'BİNGÖL', value: '12'},
    {key: '13', text: 'BİTLİS', value: '13'},
    {key: '14', text: 'BOLU', value: '14'},
    {key: '15', text: 'BURDUR', value: '15'},
    {key: '16', text: 'BURSA', value: '16'},
    {key: '17', text: 'ÇANAKKALE', value: '17'},
    {key: '18', text: 'ÇANKIRI', value: '18'},
    {key: '19', text: 'ÇORUM', value: '19'},
    {key: '20', text: 'DENİZLİ', value: '20'},
    {key: '21', text: 'DİYARBAKIR', value: '21'},
    {key: '22', text: 'EDİRNE', value: '22'},
    {key: '23', text: 'ELAZIĞ', value: '23'},
    {key: '24', text: 'ERZİNCAN', value: '24'},
    {key: '25', text: 'ERZURUM', value: '25'},
    {key: '26', text: 'ESKİŞEHİR', value: '26'},
    {key: '27', text: 'GAZİANTEP', value: '27'},
    {key: '28', text: 'GİRESUN', value: '28'},
    {key: '29', text: 'GÜMÜŞHANE', value: '29'},
    {key: '30', text: 'HAKKARİ', value: '30'},
    {key: '31', text: 'HATAY', value: '31'},
    {key: '32', text: 'ISPARTA', value: '32'},
    {key: '33', text: 'MERSİN', value: '33'},
    {key: '34', text: 'İSTANBUL', value: '34'},
    {key: '35', text: 'İZMİR', value: '35'},
    {key: '36', text: 'KARS', value: '36'},
    {key: '37', text: 'KASTAMONU', value: '37'},
    {key: '38', text: 'KAYSERİ', value: '38'},
    {key: '39', text: 'KIRKLARELİ', value: '39'},
    {key: '40', text: 'KIRŞEHİR', value: '40'},
    {key: '41', text: 'KOCAELİ', value: '41'},
    {key: '42', text: 'KONYA', value: '42'},
    {key: '43', text: 'KÜTAHYA', value: '43'},
    {key: '44', text: 'MALATYA', value: '44'},
    {key: '45', text: 'MANİSA', value: '45'},
    {key: '46', text: 'KAHRAMANMARAŞ', value: '46'},
    {key: '47', text: 'MARDİN', value: '47'},
    {key: '48', text: 'MUĞLA', value: '48'},
    {key: '49', text: 'MUŞ', value: '49'},
    {key: '50', text: 'NEVŞEHİR', value: '50'},
    {key: '51', text: 'NİĞDE', value: '51'},
    {key: '52', text: 'ORDU', value: '52'},
    {key: '53', text: 'RİZE', value: '53'},
    {key: '54', text: 'SAKARYA', value: '54'},
    {key: '55', text: 'SAMSUN', value: '55'},
    {key: '56', text: 'SİİRT', value: '56'},
    {key: '57', text: 'SİNOP', value: '57'},
    {key: '58', text: 'SİVAS', value: '58'},
    {key: '59', text: 'TEKİRDAĞ', value: '59'},
    {key: '60', text: 'TOKAT', value: '60'},
    {key: '61', text: 'TRABZON', value: '61'},
    {key: '62', text: 'TUNCELİ', value: '62'},
    {key: '63', text: 'ŞANLIURFA', value: '63'},
    {key: '64', text: 'UŞAK', value: '64'},
    {key: '65', text: 'VAN', value: '65'},
    {key: '66', text: 'YOZGAT', value: '66'},
    {key: '67', text: 'ZONGULDAK', value: '67'},
    {key: '68', text: 'AKSARAY', value: '68'},
    {key: '69', text: 'BAYBURT', value: '69'},
    {key: '70', text: 'KARAMAN', value: '70'},
    {key: '71', text: 'KIRIKKALE', value: '71'},
    {key: '72', text: 'BATMAN', value: '72'},
    {key: '73', text: 'ŞIRNAK', value: '73'},
    {key: '74', text: 'BARTIN', value: '74'},
    {key: '75', text: 'ARDAHAN', value: '75'},
    {key: '76', text: 'IĞDIR', value: '76'},
    {key: '77', text: 'YALOVA', value: '77'},
    {key: '78', text: 'KARABÜK', value: '78'},
    {key: '79', text: 'KİLİS', value: '79'},
    {key: '80', text: 'OSMANİYE', value: '80'},
    {key: '81', text: 'DÜZCE', value: '81'},
]
